import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { ArrowLeft } from "lucide-react";
import { useNavigate } from "react-router-dom";
import SentimentPill from "@/components/shared/SentimentPill";
import SentimentChart from "@/components/shared/SentimentChart";
import CommentWithReply from "@/components/shared/CommentWithReply";

interface VideoDetailPageProps {
  videoTitle: string;
  publishedAt: string;
  sentimentSummary: string;
  plan: "free" | "pro";
}

const mockPositiveComments = [
  {
    commenterHandle: "@filmnerd92",
    timestamp: "2h ago",
    likes: 34,
    originalText: "This tutorial saved my project! The production quality is insane. Best filmmaking channel on YouTube hands down 🔥",
  },
  {
    commenterHandle: "@techsteve",
    timestamp: "5h ago",
    likes: 89,
    originalText: "Just wanted to say thanks for mentioning Riverside in this video. I've been using it since your recommendation and it's a game changer for my podcast!",
  },
  {
    commenterHandle: "@creativemind",
    timestamp: "8h ago",
    likes: 12,
    originalText: "The editing in this is next level. Can't believe you did this in 10 minutes. Definitely stealing some of these techniques!",
  },
];

const mockNegativeComments = [
  {
    commenterHandle: "@criticalviewer",
    timestamp: "3h ago",
    likes: 7,
    originalText: "The audio quality was pretty rough in the outdoor shots. Maybe invest in a better lav mic? Otherwise great content.",
  },
  {
    commenterHandle: "@honestfeedback",
    timestamp: "6h ago",
    likes: 15,
    originalText: "Not a fan of the clickbait title. The video was good but didn't really match what you promised in the thumbnail.",
  },
];

const VideoDetailPage = ({
  videoTitle = "How I Film Cinematic B-Roll in 10 Minutes",
  publishedAt = "2 days ago",
  sentimentSummary = "Mostly positive. Viewers love the mic quality and editing.",
  plan,
}: VideoDetailPageProps) => {
  const navigate = useNavigate();

  return (
    <div className="space-y-6">
      {/* Back button */}
      <Button
        variant="ghost"
        size="sm"
        onClick={() => navigate("/app/videos")}
        className="gap-2"
      >
        <ArrowLeft className="w-4 h-4" />
        Back to Videos
      </Button>

      {/* Video header card */}
      <div className="rounded-2xl border border-border bg-card p-6">
        <div className="flex gap-6">
          {/* Thumbnail */}
          <div className="flex-shrink-0 w-64 h-36 rounded-xl overflow-hidden bg-muted">
            <img
              src="https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=512&h=288&fit=crop"
              alt={videoTitle}
              className="w-full h-full object-cover"
            />
          </div>

          {/* Info */}
          <div className="flex-1">
            <h1 className="text-2xl font-bold mb-2">{videoTitle}</h1>
            <p className="text-sm text-muted-foreground mb-4">{publishedAt}</p>
            <div className="mb-4">
              <SentimentPill sentiment="Positive" score={0.78} />
            </div>
          </div>
        </div>
      </div>

      {/* Sentiment Analysis - Two Cards Side by Side */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Pie Chart Card */}
        <Card className="rounded-2xl border-border">
          <CardHeader>
            <CardTitle>Comment Sentiment</CardTitle>
            <CardDescription>
              Distribution of comment sentiment
            </CardDescription>
          </CardHeader>
          <CardContent>
            <SentimentChart positive={78} neutral={15} negative={7} />
            {/* TODO: POST /api/analyze-comments for this specific video ID */}
          </CardContent>
        </Card>

        {/* AI Summary Card */}
        <Card className="rounded-2xl border-border">
          <CardHeader>
            <CardTitle>AI Summary</CardTitle>
            <CardDescription>
              AI-powered analysis of comments
            </CardDescription>
          </CardHeader>
          <CardContent>
            <p className="text-sm text-muted-foreground leading-relaxed">
              Overall, the response to this video is highly positive. Viewers are praising the production quality, 
              editing techniques, and practical advice. Multiple comments highlight the "10-minute" workflow as 
              game-changing. Some constructive feedback mentions audio quality in outdoor shots and a mismatch 
              between the title and content. Several viewers are asking about specific gear (LUTs, lighting setup) 
              and requesting follow-up tutorials on color grading.
            </p>
            {/* TODO: Generated by POST /api/analyze-comments with GPT-4o-mini */}
          </CardContent>
        </Card>
      </div>

      {/* Top Positive Comments */}
      <div>
        <h2 className="text-xl font-semibold mb-4 flex items-center gap-2">
          <span className="text-success">✓</span> Top Positive Comments
        </h2>
        <div className="space-y-3">
          {mockPositiveComments.map((comment, idx) => (
            <CommentWithReply key={idx} {...comment} sentiment="positive" />
          ))}
        </div>
      </div>

      {/* Top Negative Comments */}
      <div>
        <h2 className="text-xl font-semibold mb-4 flex items-center gap-2">
          <span className="text-destructive">!</span> Top Negative Comments
        </h2>
        <div className="space-y-3">
          {mockNegativeComments.map((comment, idx) => (
            <CommentWithReply key={idx} {...comment} sentiment="negative" />
          ))}
        </div>
      </div>
    </div>
  );
};

export default VideoDetailPage;
